apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: memphis
  labels:
    app: broker
spec:
  type: LoadBalancer
  ports:
  - port: 6666
    targetPort: 6666
    protocol: TCP
    name: clients
  - port: 7770
    targetPort: 7770
    protocol: TCP
    name: websocket
  - port: 8222
    targetPort: 8222
    protocol: TCP
    name: monitoring
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: dashboard
  selector:
    app: broker
