apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: memphis
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongo
          image: memphisos/mongo:4.2
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 27017

